// <auto-generated />
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180220065351_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotesCreatorDTO.ConsultantDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Consultants");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ConsultantDTO");
                });

            modelBuilder.Entity("NotesCreatorDTO.NoteActionDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActionDate");

                    b.Property<int>("ActionNameID");

                    b.Property<string>("ActionNote");

                    b.Property<bool>("Callback");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("NoteID");

                    b.Property<bool>("Urgent");

                    b.HasKey("ID");

                    b.HasIndex("ActionNameID");

                    b.HasIndex("NoteID")
                        .IsUnique();

                    b.ToTable("NoteActionDTO");

                    b.HasDiscriminator<string>("Discriminator").HasValue("NoteActionDTO");
                });

            modelBuilder.Entity("NotesCreatorDTO.NoteDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConsultantNameID");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("MainNote")
                        .IsRequired()
                        .HasColumnName("Note");

                    b.HasKey("ID");

                    b.HasIndex("ConsultantNameID");

                    b.ToTable("Notes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("NoteDTO");
                });

            modelBuilder.Entity("Backend.Models.Consultant", b =>
                {
                    b.HasBaseType("NotesCreatorDTO.ConsultantDTO");


                    b.ToTable("Consultants");

                    b.HasDiscriminator().HasValue("Consultant");
                });

            modelBuilder.Entity("Backend.Models.NoteAction", b =>
                {
                    b.HasBaseType("NotesCreatorDTO.NoteActionDTO");


                    b.ToTable("NoteAction");

                    b.HasDiscriminator().HasValue("NoteAction");
                });

            modelBuilder.Entity("Backend.Models.Note", b =>
                {
                    b.HasBaseType("NotesCreatorDTO.NoteDTO");


                    b.ToTable("Notes");

                    b.HasDiscriminator().HasValue("Note");
                });

            modelBuilder.Entity("NotesCreatorDTO.NoteActionDTO", b =>
                {
                    b.HasOne("NotesCreatorDTO.ConsultantDTO", "ActionName")
                        .WithMany()
                        .HasForeignKey("ActionNameID");

                    b.HasOne("NotesCreatorDTO.NoteDTO", "Note")
                        .WithOne("NoteAction")
                        .HasForeignKey("NotesCreatorDTO.NoteActionDTO", "NoteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NotesCreatorDTO.NoteDTO", b =>
                {
                    b.HasOne("NotesCreatorDTO.ConsultantDTO", "ConsultantName")
                        .WithMany()
                        .HasForeignKey("ConsultantNameID");
                });
#pragma warning restore 612, 618
        }
    }
}
